sudo: required

language: node_js
cache:
  directories:
    - "node_modules"

before_install:
  # APT
  - sudo apt -qq update
  - sudo apt install -y expect
  - npm i -g npm@6.1.0

before_script:
  - chmod +x generate.exp
  - ./generate.exp
  - cd test
  - npm ci
  - npm run generate